---

- name: Manage ping
  hosts: ping
  tasks:
    - name: Test to ping via playbook
      ansible.builtin.ping:
      register: ping

    - name: Ping result
      ansible.builtin.debug:
        var: ping
